---
title: "Day 3 Comp Session 2"
format: html
editor: visual
---

## Vectors in R

```{r}

# if you have quotes, it is a character string, if you have a number, you are trying to input it as a number. 

marmots <- c("blue","green",4, "yellow", TRUE)

class(marmots)

marmots

#if we have values that are all numeric then you have a numeric vector
```

Making a numeric vector:

```{r}
pika <-c(24, 2.3, 5.6, 9)

class(pika)
```

```{r}
# we can have integer values or floats

# for an integer put an L after the values

bear <-c(20L, 3L, 5L, 18L)
```

## Vector addition and subtraction

```{r}
#making two new vectors

ringtail <- c(4.3, 8.9, 2.6, 7.1)
fox <- c(9.0, 12.5, 5.4, 10.9)

ringtail_fox <-ringtail +fox 

ringtail_fox

#if you're in the console, it will take you back to previously executed lines of code. 

#subtracting
ringtail_minus_fox <- ringtail - fox

ringtail_minus_fox

#scalar multiplier is changing the magnitude of that

100* ringtail

#dot product between vectors ; percent sign, asterisk, percent sign

ringtail %*% fox 
```
